#!/bin/sh
# convert dxf's to png
# sample command:
# vec2web.sh input.dxf output.png 1024
 
DIR=`pwd`
QCAD=~/.local/vec2web
 
if [ -z "$1" -o -z "$2" -o -z "$3" ] ; then
	echo $0 input.dxf output.png resolution
	exit 1
fi
 
X=$3
Y=$3
 
cd "$QCAD"
 
./vec2web "$DIR/$1" "$DIR/$2" -x $X -y $Y

cd "$DIR"