#!/bin/sh
# convert dxf's to png
# sample command:
# vec2web.sh input.dxf output.png 1024
 
DIR=`pwd`
QCAD=~/.local/vec2web/
 
if [ -z "$1" -o -z "$2" -o -z "$3" ] ; then
	echo $0 input.dxf output.ps pagesize
	exit 1
fi
 
S=$3

#echo $1
#echo $2
#echo $3

#echo cd $QCAD
cd "$QCAD"
 
./vec2web "$DIR/$1" "$DIR/$2" -s $S
#echo cd $DIR

cd "$DIR"

#echo ps2pdf $2
ps2pdf "$2"

